name: pr

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'master'

jobs:
  test-build:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build
        run: |
          DOCKER_BUILDKIT=1 docker build --force-rm --no-cache --network=host --build-arg NODE_ENV=production .